from datetime import datetime
from pathlib import Path
from collections import Counter

from docx import Document
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.shared import Pt, RGBColor

from backend.services.legal_ai import generate_structured_summary

ROLE_COLORS = {
    "JUDGE": RGBColor(0x1A, 0x56, 0xDB),
    "ADVOCATE": RGBColor(0x05, 0x96, 0x69),
    "WITNESS": RGBColor(0xD9, 0x77, 0x06),
    "ACCUSED": RGBColor(0xB4, 0x53, 0x09),
    "CULPRIT": RGBColor(0xB4, 0x53, 0x09),
    "OTHER": RGBColor(0x47, 0x55, 0x69),
    "UNKNOWN": RGBColor(0x6B, 0x72, 0x80),
}


def generate_docx(utterances: list[dict], session_hash: str = "NO_SESSION") -> str:
    out_dir = Path(__file__).resolve().parents[1] / "database"
    out_dir.mkdir(parents=True, exist_ok=True)
    output_path = out_dir / "VaakShastra_Record.docx"

    doc = Document()
    summary_data = generate_structured_summary(utterances)
    by_role = Counter(u.get("role", "UNKNOWN") for u in utterances)

    title = doc.add_heading("DISTRICT COURT PROCEEDINGS RECORD", 0)
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER

    doc.add_paragraph(f"Date: {datetime.now().strftime('%d %B %Y')}")
    doc.add_paragraph(f"Generated by: VaakShastra AI")
    doc.add_paragraph(f"Total Utterances: {len(utterances)}")
    doc.add_paragraph(f"Speaker Distribution: {dict(by_role)}")
    doc.add_paragraph("-" * 55)

    # Section 1: Hearing Summary
    doc.add_heading("1. Hearing Summary", level=1)
    for line in str(summary_data.get("summary", "")).splitlines():
        cleaned = line.strip()
        if cleaned:
            doc.add_paragraph(cleaned)

    # Section 2: Key Orders / Court Directions
    doc.add_heading("2. Key Orders And Directions", level=1)
    key_orders = summary_data.get("key_orders", [])
    if key_orders:
        for order in key_orders:
            doc.add_paragraph(order, style="List Bullet")
    else:
        doc.add_paragraph("No explicit order lines detected.")

    # Section 3: Chronological Transcript
    doc.add_heading("3. Chronological Transcript", level=1)

    for utterance in utterances:
        role = utterance.get("role", "UNKNOWN")

        para = doc.add_paragraph()
        role_run = para.add_run(f"[{role} - {utterance.get('timestamp', '')}]  ")
        role_run.bold = True
        role_run.font.color.rgb = ROLE_COLORS.get(role, ROLE_COLORS["UNKNOWN"])
        role_run.font.size = Pt(10)

        type_run = para.add_run(f"({utterance.get('type', 'STATEMENT')})\n")
        type_run.italic = True
        type_run.font.size = Pt(9)

        text_run = para.add_run(utterance.get("text", ""))
        text_run.font.size = Pt(11)

        doc.add_paragraph()

    # Section 4: Role-wise Transcript Blocks
    doc.add_heading("4. Speaker-Wise Transcript", level=1)
    grouped: dict[str, list[dict]] = {}
    for utterance in utterances:
        grouped.setdefault(utterance.get("role", "UNKNOWN"), []).append(utterance)

    for role, role_items in grouped.items():
        role_heading = doc.add_paragraph(f"{role} ({len(role_items)} lines)")
        role_heading.runs[0].bold = True
        for item in role_items:
            line = f"[{item.get('timestamp', '')}] {item.get('text', '')}"
            doc.add_paragraph(line, style="List Bullet")

    doc.add_paragraph("-" * 55)
    doc.add_paragraph(f"Record Hash: {session_hash}")
    doc.add_paragraph("Tamper-evident record. Modifying content changes the hash.")

    doc.save(str(output_path))
    return str(output_path)
