from datetime import datetime
from pathlib import Path

from docx import Document
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.shared import Pt, RGBColor

ROLE_COLORS = {
    "JUDGE": RGBColor(0x1A, 0x56, 0xDB),
    "ADVOCATE": RGBColor(0x05, 0x96, 0x69),
    "WITNESS": RGBColor(0xD9, 0x77, 0x06),
    "UNKNOWN": RGBColor(0x6B, 0x72, 0x80),
}


def generate_docx(utterances: list[dict], session_hash: str = "NO_SESSION") -> str:
    out_dir = Path(__file__).resolve().parents[1] / "database"
    out_dir.mkdir(parents=True, exist_ok=True)
    output_path = out_dir / "VaakShastra_Record.docx"

    doc = Document()

    title = doc.add_heading("DISTRICT COURT PROCEEDINGS RECORD", 0)
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER

    doc.add_paragraph(f"Date: {datetime.now().strftime('%d %B %Y')}")
    doc.add_paragraph(f"Generated by: VaakShastra AI")
    doc.add_paragraph(f"Total Utterances: {len(utterances)}")
    doc.add_paragraph("-" * 55)

    for utterance in utterances:
        role = utterance.get("role", "UNKNOWN")

        para = doc.add_paragraph()
        role_run = para.add_run(f"[{role} - {utterance.get('timestamp', '')}]  ")
        role_run.bold = True
        role_run.font.color.rgb = ROLE_COLORS.get(role, ROLE_COLORS["UNKNOWN"])
        role_run.font.size = Pt(10)

        type_run = para.add_run(f"({utterance.get('type', 'STATEMENT')})\n")
        type_run.italic = True
        type_run.font.size = Pt(9)

        text_run = para.add_run(utterance.get("text", ""))
        text_run.font.size = Pt(11)

        doc.add_paragraph()

    doc.add_paragraph("-" * 55)
    doc.add_paragraph(f"Record Hash: {session_hash}")
    doc.add_paragraph("Tamper-evident record. Modifying content changes the hash.")

    doc.save(str(output_path))
    return str(output_path)
